name: MiraLib

on:
  push:
    branches: [ master ]
    paths:
      - 'src/tools/miralib/csharp/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/tools/miralib/csharp/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: |
        cd src/tools/miralib/csharp
        dotnet restore
    - name: Build
      run: |
        cd src/tools/miralib/csharp
        dotnet build --configuration Release --no-restore MiraLib.csproj
    - name: Upload miralib dll
      uses: actions/upload-artifact@v2
      with:
        name: miralib.dll
        path: src/tools/miralib/csharp/bin/Release/netcoreapp3.1/MiraLib.dll
